In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#default_exp search

In [3]:
#export
from food.tools import *
from food.paths import *
from food.psql import *
import requests
from food.qdrant import *
import torch
from torch.nn import CosineSimilarity
cos = CosineSimilarity(dim=1, eps=1e-08)
import numpy as np

In [4]:
#export
## temp while api is not aperational
# from food.clipmodel import *
from PIL import Image

In [5]:
# #export
# foods = read_sql('foods')
# # foods = foods.drop(columns = ['clip'])
# foods = foods.set_index('id')

In [6]:
#export
collection_name = 'food_images'
table = 'foods_prompted'
foods = read_sql(table)
foods = foods.set_index('id')

In [7]:
#export
def read_image_from_url(url=None):
    response = requests.get(url, stream=True)
    return Image.open(response.raw)


In [8]:
env = 'prod'

In [11]:
url = 'https://www.applesfromny.com/wp-content/uploads/2020/06/SnapdragonNEW.png'

In [16]:
#export
def search_image_(url=None,head = 1,env='dev'):
    client = dev_client if env == 'dev' else prod_client
    image_clip = requests.post(f'https://guru.skynet.center/image2vector/?url={url}').json()
    results = client.search(collection_name=collection_name,query_vector=image_clip,top=head)
    image_clip = torch.Tensor(image_clip)
    df = foods.loc[[r.id for r in results]].copy()
    df['score'] = [r.score for r in results]
    df = df.sort_values('score',ascending=False)

    return image_clip,df.reset_index()

series2tensor = lambda series:torch.tensor([np.array(c) for c in series.values])

In [17]:
#export
drop_vector =      lambda clip, i: torch.cat([clip[0:i], clip[i+1:]])

def multiply_vector(clip,i,n=1):
    duplicated = torch.cat([clip[i].reshape(1,768) for _ in range(n)])
    return torch.cat([clip, duplicated.reshape(n,768)])

In [18]:
#export

def multiple_foods(url,env='dev'):

    image_clip,selected = search_image_(url,head=100,env=env)
    selected=selected.reset_index(drop=True)
    clip = series2tensor(selected['clip'])
    initscore = cos(image_clip.reshape(1,768), clip.mean(0).reshape(1,768))

    startscore = initscore.detach().clone()-0.0000001

    while startscore !=initscore:
        startscore = initscore.detach().clone()
        
        selected = selected.reset_index(drop=True)
        for i in reversed(selected.index):
            clip = series2tensor(selected['clip'])
            dropped = drop_vector(clip,i)
            testscore = cos(image_clip.reshape(1,768), dropped.mean(0).reshape(1,768))

            if testscore > initscore-0.0001: 
                r = selected.loc[i,'text']
                selected = selected.drop(i)
                initscore = testscore

            else:
                extra = multiply_vector(clip,i,1)
                testscore = cos(image_clip.reshape(1,768), extra.mean(0).reshape(1,768))
                if testscore > initscore: 
                    selected = selected.append(selected.loc[i])
                    initscore = testscore


            

        print(initscore)
    count = selected.groupby('text')['clip'].count().sort_index()
    r = selected.drop_duplicates('text').set_index("text").sort_index()
    r['count'] = count
    r = r.sort_values('count',ascending = False)
    r['cumcount'] = r['count'].cumsum()/r['count'].sum()

    description = '. '.join(r[r['cumcount']<0.9]['description'].unique().tolist()) 


    return r.drop(columns = ['clip']), description, selected,initscore

In [19]:
#export
def search_image(url,env='dev'):
    r, desc, sel,score = multiple_foods(url,env=env)
    df = sel[['energy','protein','carb','fat','score']].mean().to_frame().T
    df['score'] =score
    df['description'] = desc
    return df.round()


In [20]:
url = 'https://image.shutterstock.com/image-photo/red-apple-isolated-on-white-600w-1728480094.jpg'

In [21]:
search_image(url,env='prod')

/tmp/ipykernel_136362/3265430290.py:13: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_new.cpp:201.)
  series2tensor = lambda series:torch.tensor([np.array(c) for c in series.values])


tensor([0.2346], dtype=torch.float64)
tensor([0.2524], dtype=torch.float64)
tensor([0.2549], dtype=torch.float64)
tensor([0.2550], dtype=torch.float64)
tensor([0.2550], dtype=torch.float64)


energy  protein  carb  fat  score description
0    79.0      1.0  19.0  1.0    0.0  Apple, raw

In [2]:
!nbdev_build_lib

Converted 00_clipmodel.ipynb.
Converted 00_custom_pandas.ipynb.
Converted 00_paths.ipynb.
Converted 00_progress_check.ipynb.
Converted 00_psql.ipynb.
Converted 00_qdrant.ipynb.
Converted 00_tools.ipynb.
Converted 01_search.ipynb.
Converted inference.ipynb.
Converted stats.ipynb.
