In [4]:
from food.tools import *
from food.paths import *
from food.psql import *

import pandas as pd
import numpy as np
from pathlib import Path

# !nbdev_build_lib

In [5]:
photos_path = testset_path/'test_photos'

In [7]:
testdf = pd.read_csv(testset_path/'test_set.csv')

testdf.columns = ['name_f','fat_f','protein_f','carbs_f','energy_f','','','','','weight_f','','url']
testdf = testdf.drop(columns = [c for c in testdf.columns if c == ''])
for c in ['fat_f','protein_f','energy_f','weight_f','carbs_f']:
    testdf[c] = testdf[c].str.replace(',','.').astype('float64')
testdf['url'] = testdf['url'].apply(lambda id:f"https://glovo.away.guru/test_photos/{id}.jpeg")

In [8]:
from food.search import *

In [30]:
r = []
fact = testdf.sample(10).reset_index(drop=True)
for image in fact['url'].tolist():
    r.append(search_image(image,env='prod'))
rr = fact.join(pd.concat(r).reset_index(drop=True))
rrr = rr[['energy_f','energy','url','description']]
rrr['error'] = (rrr['energy_f']/rrr['energy']-1).abs()
rrr = rrr.sort_values('error',ascending = False).reset_index(drop=True)


tensor([0.2510], dtype=torch.float64)
tensor([0.2613], dtype=torch.float64)
tensor([0.2627], dtype=torch.float64)
tensor([0.2628], dtype=torch.float64)
tensor([0.2628], dtype=torch.float64)
tensor([0.2628], dtype=torch.float64)
tensor([0.2682], dtype=torch.float64)
tensor([0.2851], dtype=torch.float64)
tensor([0.2863], dtype=torch.float64)
tensor([0.2864], dtype=torch.float64)
tensor([0.2862], dtype=torch.float64)
tensor([0.2863], dtype=torch.float64)
tensor([0.2863], dtype=torch.float64)
tensor([0.2650], dtype=torch.float64)
tensor([0.2687], dtype=torch.float64)
tensor([0.2699], dtype=torch.float64)
tensor([0.2700], dtype=torch.float64)
tensor([0.2700], dtype=torch.float64)
tensor([0.2460], dtype=torch.float64)
tensor([0.2684], dtype=torch.float64)
tensor([0.2684], dtype=torch.float64)
tensor([0.2377], dtype=torch.float64)
tensor([0.2542], dtype=torch.float64)
tensor([0.2566], dtype=torch.float64)
tensor([0.2568], dtype=torch.float64)
tensor([0.2568], dtype=torch.float64)
tensor([0.29

/tmp/ipykernel_1054155/633827319.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rrr['error'] = (rrr['energy_f']/rrr['energy']-1).abs()


energy_f  energy                                                url  \
0    328.85   148.0  https://glovo.away.guru/test_photos/52ccafcc-e...   
2    108.85   239.0  https://glovo.away.guru/test_photos/ecc8590f-a...   
5    297.30   215.0  https://glovo.away.guru/test_photos/9a0acde1-3...   
4    261.32   189.0  https://glovo.away.guru/test_photos/1855845c-5...   
6    151.69   118.0  https://glovo.away.guru/test_photos/748d5921-3...   
3     59.88    72.0  https://glovo.away.guru/test_photos/1f111c7e-d...   
1    104.19   123.0  https://glovo.away.guru/test_photos/638301ac-0...   
7    142.55   127.0  https://glovo.away.guru/test_photos/84dc856a-f...   
8    255.40   237.0  https://glovo.away.guru/test_photos/6cc34ea4-6...   
9    220.22   234.0  https://glovo.away.guru/test_photos/1cce4755-4...   

                                         description     error  
0  Tuna, fresh, coated, fried. Sushi roll, Califo...  1.221959  
2  Chicken "wings" with other sauces or seasoning...  0.544561  
5  Pasta with cream sauce, poultry, and added veg...  0.382791  
4     Pie, pear, individual size or tart. Basil, raw  0.382646  
6  Wrap sandwich, filled with vegetables. Sushi r...  0.285508  
3  Pasta with tomato-based sauce, and added veget...  0.168333  
1  Seaweed, dried. Bitter melon, horseradish, jut...  0.152927  
7  Sushi roll, California. Sushi, topped with sal...  0.122441  
8  Pizza with pepperoni, from restaurant or fast ...  0.077637  
9  Egg and ham on biscuit. Crepe, filled with mea...  0.058889

In [ ]:
ккк

In [37]:
rrr.iloc[2]

energy_f                                                   297.3
energy                                                     215.0
url            https://glovo.away.guru/test_photos/9a0acde1-3...
description    Pasta with cream sauce, poultry, and added veg...
error                                                   0.382791
Name: 5, dtype: object

In [38]:
get_image_from_url(rrr.iloc[2]['url'])